name: Release to SNAPSHOTS Maven Central

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 2am

jobs:
  snapshots:
    name: Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRHUSERNAME
          server-password: OSSRHPASSWORD
          gpg-private-key: ${{ secrets.SIGNINGKEY }}
          gpg-passphrase: SIGNINGPASSWORD
      - name: Build
        run: make build-all
      - name: Maven SNAPSHOT Release
        run: mvn -Prelease clean deploy
        env:
          OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
          OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
